modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"
issueTrackerURL="https://github.com/TheMillman/MiningUtils/issues"

[[mods]]
modId="miningutils"
version="${file.jarVersion}"
displayName="Mining Utils"
updateJSONURL="https://raw.githubusercontent.com/TheMillman/MiningUtils/1.19.x/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/miningutils"
logoFile="logo.png"
authors="The_Millman"
description='''
This mod adds different blocks and items for a easy way to farming resources in Minecraft.
'''

[[dependencies.miningutils]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.miningutils]] 
    modId="themillmanlib" 
    mandatory=true 
    versionRange="[1.19.4-0.2.1,1.19.4-0.2.2)"
    ordering="NONE"
    side="BOTH"   
    
[[dependencies.miningutils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
